/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg5_marcelarivera;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Mvrivera
 */
public class Lab5_marcelarivera extends javax.swing.JFrame {

    public Lab5_marcelarivera() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaginaPrincipal = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        super_nombre = new javax.swing.JTextField();
        super_edad = new javax.swing.JTextField();
        super_planeta = new javax.swing.JTextField();
        super_altura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        villa_nombre = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        villa_edad = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        villa_planeta = new javax.swing.JTextField();
        villa_altura = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSuperpoderes = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        poder_descri = new javax.swing.JTextArea();
        mortal_Si = new javax.swing.JRadioButton();
        mortal_No = new javax.swing.JRadioButton();
        poder_nivel = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ListaSuperHeroes = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        ListaSuperVillanos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        Arbol = new javax.swing.JTree();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        Eliminar = new javax.swing.JMenu();
        buttonGroup2 = new javax.swing.ButtonGroup();
        UsuarioT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        contrat = new javax.swing.JPasswordField();

        jPanel1.setLayout(null);
        jPanel1.add(super_nombre);
        super_nombre.setBounds(160, 80, 230, 40);
        jPanel1.add(super_edad);
        super_edad.setBounds(161, 132, 230, 40);
        jPanel1.add(super_planeta);
        super_planeta.setBounds(161, 181, 230, 40);

        super_altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                super_alturaActionPerformed(evt);
            }
        });
        jPanel1.add(super_altura);
        super_altura.setBounds(161, 233, 230, 30);

        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(23, 92, 48, 16);

        jLabel4.setText("Edad:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(23, 152, 31, 16);

        jLabel5.setText("Planeta Origen:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(23, 201, 87, 16);

        jLabel6.setText("Altura:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(23, 243, 37, 16);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(83, 29, 0, 0);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("CREAR SUPERHEROE");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(161, 35, 148, 19);

        jButton2.setText("Agregar ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(161, 287, 79, 32);

        jLabel9.setText("Nombre:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(23, 407, 48, 16);

        jLabel10.setText("Edad:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(23, 474, 31, 16);

        jLabel11.setText("Planeta Origen:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(23, 537, 87, 16);

        jLabel12.setText("Altura:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(23, 593, 37, 16);
        jPanel1.add(villa_nombre);
        villa_nombre.setBounds(161, 405, 230, 40);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("CREAR SUPERVILLANO");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(161, 350, 158, 19);
        jPanel1.add(villa_edad);
        villa_edad.setBounds(161, 463, 230, 38);

        jButton3.setText("Agregar ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(161, 644, 79, 32);
        jPanel1.add(villa_planeta);
        villa_planeta.setBounds(161, 526, 230, 38);

        villa_altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                villa_alturaActionPerformed(evt);
            }
        });
        jPanel1.add(villa_altura);
        villa_altura.setBounds(161, 582, 230, 38);

        tablaSuperpoderes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion", "Mortal", "Nivel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaSuperpoderes);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(420, 50, 510, 640);

        jLabel14.setText("SUPERPODERES");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(420, 20, 110, 16);

        jTabbedPane1.addTab("Agregar SuperHeroe", jPanel1);

        poder_descri.setColumns(20);
        poder_descri.setRows(5);
        jScrollPane2.setViewportView(poder_descri);

        buttonGroup2.add(mortal_Si);
        mortal_Si.setSelected(true);
        mortal_Si.setText("Si ");

        buttonGroup2.add(mortal_No);
        mortal_No.setText("No");

        poder_nivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " -------------------------------", "1", "2", "3", "4", "5" }));

        jLabel15.setText("Nivel Poder:");

        jLabel16.setText("Descripcion:");

        jLabel17.setText("Mortal:");

        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setText("CREAR PODER");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(65, 65, 65)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(mortal_Si)
                            .addGap(18, 18, 18)
                            .addComponent(mortal_No, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                        .addComponent(poder_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel18)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poder_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mortal_Si)
                    .addComponent(mortal_No)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar SuperPoder", jPanel3);

        jLabel19.setText("SUPERHEROES");

        jLabel20.setText("SUPERVILLANOS");

        ListaSuperHeroes.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(ListaSuperHeroes);

        ListaSuperVillanos.setModel(new DefaultListModel());
        jScrollPane6.setViewportView(ListaSuperVillanos);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        Arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(Arbol);

        jButton5.setText("------------------>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("------------------>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6)
                    .addComponent(jScrollPane5)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jButton6)))
                        .addGap(82, 82, 82)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(142, 142, 142))))
                    .addComponent(jScrollPane3))
                .addGap(50, 50, 50))
        );

        jTabbedPane1.addTab("Arbol y Lista", jPanel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable2);

        jLabel21.setText("S");

        jLabel22.setText("jLabel22");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(289, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar a grupo", jPanel4);

        javax.swing.GroupLayout PaginaPrincipalLayout = new javax.swing.GroupLayout(PaginaPrincipal.getContentPane());
        PaginaPrincipal.getContentPane().setLayout(PaginaPrincipalLayout);
        PaginaPrincipalLayout.setHorizontalGroup(
            PaginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaginaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        PaginaPrincipalLayout.setVerticalGroup(
            PaginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaginaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jMenu1.setText("jMenu1");
        jPopupMenu1.add(jMenu1);

        Eliminar.setText("jMenu2");
        jPopupMenu1.add(Eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UsuarioT)
                            .addComponent(contrat, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuarioT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(contrat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void llenarTabla() {
        DefaultTableModel po = (DefaultTableModel) tablaSuperpoderes.getModel();

        for (int i = po.getRowCount() - 1; i >= 0; i--) {
            po.removeRow(i);
        }

        for (Poderes i : poderes) {
            Object[] poder = {i.getDescripcion(), i.getMortal(), i.getNivelpoder()};
            po.addRow(poder);
        }

        tablaSuperpoderes.setModel(po);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PaginaPrincipal.pack();
        PaginaPrincipal.setVisible(true);
        PaginaPrincipal.setLocationRelativeTo(this);
        this.setVisible(false);
        /* if (UsuarioT.getText().equals("stanlee") && contrat.getText().equals("spiderman99")) {
            PaginaPrincipal.pack();
            PaginaPrincipal.setVisible(true);
            PaginaPrincipal.setLocationRelativeTo(this);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Contraseña o usuario incorrecto");
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void super_alturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_super_alturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_super_alturaActionPerformed

    private void villa_alturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_villa_alturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_villa_alturaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Superheroes p = new Superheroes(super_nombre.getText(), super_planeta.getText(), Integer.parseInt(super_edad.getText()), Double.parseDouble(super_altura.getText()));
        p.setEquipo("Vengadores");
        superheroe.add(p);
        DefaultListModel modelo = (DefaultListModel) ListaSuperHeroes.getModel();
        modelo.addElement(p);
          p=new Superheroes("pato", "DSa", 32, 32);
         p.setEquipo("EX-MEN");
         superheroe.add(p);
        modelo.addElement(p);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        boolean u;
        if (mortal_Si.isSelected()) {
            u = true;
        } else {
            u = false;
        }
        String nivele = (String) poder_nivel.getSelectedItem();
        int nivel = Integer.parseInt(nivele);
        Poderes p = new Poderes(nivel, poder_descri.getText(), u);
        poderes.add(p);
        JOptionPane.showMessageDialog(this, "Se agrego exitosamente");
        poder_nivel.setSelectedIndex(0);
        mortal_Si.setSelected(true);
        poder_descri.setText("");
        llenarTabla();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (ListaSuperHeroes.getSelectedIndex() >= 0) {
            DefaultTreeModel modeloARBOL = (DefaultTreeModel) Arbol.getModel();
            DefaultListModel modeloLISTA = (DefaultListModel) ListaSuperHeroes.getModel();
            int posi = ListaSuperHeroes.getSelectedIndex();
            String equipo=superheroe.get(posi).getEquipo();
            System.out.println(" das "+equipo+" dsa");
            if(equipo != null){
            DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            int centinela = -1,centinela2=-1;
            for (int i = 0; i < nodo.getChildCount(); i++) {
                if (nodo.getChildAt(i).toString().equals("Superheroes")) {
                     for (int j = 0; j < nodo.getChildAt(i).getChildCount(); j++) {
                         if (nodo.getChildAt(i).getChildAt(j).toString().equals(superheroe.get(posi).getEquipo())) {
                              ((DefaultMutableTreeNode) nodo.getChildAt(i).getChildAt(j)).add(new DefaultMutableTreeNode(superheroe.get(posi)));
                              modeloARBOL.reload(nodo);
                              centinela2=1;
                         }
                     }
                      centinela = 1;
                }
            }
                System.out.println(centinela+" "+centinela2);
            if (centinela == -1) {
                DefaultMutableTreeNode n1 = new DefaultMutableTreeNode("Superheroes");
                modeloARBOL.reload(nodo); 
                nodo.add(n1);
            if(centinela2==-1){
                DefaultMutableTreeNode n2 = new DefaultMutableTreeNode(superheroe.get(posi).getEquipo());
               DefaultMutableTreeNode p1 = new DefaultMutableTreeNode(superheroe.get(posi));
                modeloARBOL.reload(nodo);
                n1.add(n2);
                n2.add(p1);  
            }
            }
            if(centinela==1){
                if(centinela2==-1){
                    for (int i = 0; i < nodo.getChildCount(); i++) {
                if (nodo.getChildAt(i).toString().equals("Superheroes")) {
                     for (int j = 0; j < nodo.getChildAt(i).getChildCount(); j++) {
                         if (nodo.getChildAt(i).getChildAt(j).toString()!=(superheroe.get(posi).getEquipo())) {
                              ((DefaultMutableTreeNode) nodo.getChildAt(i).getChildAt(j)).add(new DefaultMutableTreeNode(superheroe.get(posi)));
                              modeloARBOL.reload(nodo);
                           
                         }
                     }
                }
            }
            }
            }
            modeloARBOL.reload();      
            }else{
                JOptionPane.showMessageDialog(this, "No tiene equipo");
            }
          
        } else {
            JOptionPane.showMessageDialog(this,
                    "No hay persona seleccionada");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    
    
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (ListaSuperVillanos.getSelectedIndex() >= 0) {
            DefaultTreeModel modeloARBOL = (DefaultTreeModel) Arbol.getModel();
            DefaultListModel modeloLISTA = (DefaultListModel) ListaSuperVillanos.getModel();

            int posi = ListaSuperVillanos.getSelectedIndex();
            villanos.get(posi);
            DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            ((DefaultMutableTreeNode) nodo.getChildAt(1)).add(new DefaultMutableTreeNode(villanos.get(posi)));
            modeloARBOL.reload(nodo);

        } else {
            JOptionPane.showMessageDialog(this,
                    "No hay persona seleccionada");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Villanos p = new Villanos(villa_nombre.getText(), villa_planeta.getText(), Integer.parseInt(villa_edad.getText()), Double.parseDouble(villa_altura.getText()));
        villanos.add(p);
        DefaultListModel modelo = (DefaultListModel) ListaSuperVillanos.getModel();
        modelo.addElement(p);

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab5_marcelarivera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab5_marcelarivera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab5_marcelarivera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab5_marcelarivera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab5_marcelarivera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree Arbol;
    private javax.swing.JMenu Eliminar;
    private javax.swing.JList<String> ListaSuperHeroes;
    private javax.swing.JList<String> ListaSuperVillanos;
    private javax.swing.JFrame PaginaPrincipal;
    private javax.swing.JTextField UsuarioT;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPasswordField contrat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton mortal_No;
    private javax.swing.JRadioButton mortal_Si;
    private javax.swing.JTextArea poder_descri;
    private javax.swing.JComboBox<String> poder_nivel;
    private javax.swing.JTextField super_altura;
    private javax.swing.JTextField super_edad;
    private javax.swing.JTextField super_nombre;
    private javax.swing.JTextField super_planeta;
    private javax.swing.JTable tablaSuperpoderes;
    private javax.swing.JTextField villa_altura;
    private javax.swing.JTextField villa_edad;
    private javax.swing.JTextField villa_nombre;
    private javax.swing.JTextField villa_planeta;
    // End of variables declaration//GEN-END:variables
ArrayList<Superheroes> superheroe = new ArrayList();
    ArrayList<Villanos> villanos = new ArrayList();
    ArrayList<Poderes> poderes = new ArrayList();
}
