/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg5_marcelarivera;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Mvrivera
 */
public class Lab5_marcelarivera extends javax.swing.JFrame {

    public Lab5_marcelarivera() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaginaPrincipal = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        super_nombre = new javax.swing.JTextField();
        super_edad = new javax.swing.JTextField();
        super_planeta = new javax.swing.JTextField();
        super_altura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        villa_nombre = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        villa_edad = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        villa_planeta = new javax.swing.JTextField();
        villa_altura = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSuperpoderes = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        poder_descri = new javax.swing.JTextArea();
        mortal_Si = new javax.swing.JRadioButton();
        mortal_No = new javax.swing.JRadioButton();
        poder_nivel = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ListaSuperHeroes = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        ListaSuperVillanos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        Arbol = new javax.swing.JTree();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaSuperheroes = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        TablaSuperVillanos = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        superequipo = new javax.swing.JComboBox<>();
        villaequipo = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        AgregarAlArbol = new javax.swing.JPopupMenu();
        AgregarHeroe = new javax.swing.JMenu();
        AgregarAlArbolVillano = new javax.swing.JPopupMenu();
        AgregarVillano = new javax.swing.JMenu();
        UsuarioT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        contrat = new javax.swing.JPasswordField();

        jPanel1.setLayout(null);
        jPanel1.add(super_nombre);
        super_nombre.setBounds(160, 80, 230, 40);
        jPanel1.add(super_edad);
        super_edad.setBounds(161, 132, 230, 40);
        jPanel1.add(super_planeta);
        super_planeta.setBounds(161, 181, 230, 40);

        super_altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                super_alturaActionPerformed(evt);
            }
        });
        jPanel1.add(super_altura);
        super_altura.setBounds(161, 233, 230, 30);

        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(23, 92, 48, 16);

        jLabel4.setText("Edad:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(23, 152, 80, 16);

        jLabel5.setText("Planeta Origen:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(23, 201, 87, 16);

        jLabel6.setText("Altura:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(23, 243, 37, 16);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(83, 29, 0, 0);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("CREAR SUPERHEROE");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(161, 35, 148, 19);

        jButton2.setText("Agregar ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(310, 280, 79, 32);

        jLabel9.setText("Nombre:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(23, 407, 48, 16);

        jLabel10.setText("Edad:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(23, 474, 31, 16);

        jLabel11.setText("Planeta Origen:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(23, 537, 87, 16);

        jLabel12.setText("Altura:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(23, 593, 37, 16);
        jPanel1.add(villa_nombre);
        villa_nombre.setBounds(161, 405, 230, 40);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("CREAR SUPERVILLANO");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(161, 350, 158, 19);
        jPanel1.add(villa_edad);
        villa_edad.setBounds(161, 463, 230, 38);

        jButton3.setText("Agregar ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(310, 640, 79, 32);
        jPanel1.add(villa_planeta);
        villa_planeta.setBounds(161, 526, 230, 38);

        villa_altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                villa_alturaActionPerformed(evt);
            }
        });
        jPanel1.add(villa_altura);
        villa_altura.setBounds(161, 582, 230, 38);

        tablaSuperpoderes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion", "Mortal", "Nivel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaSuperpoderes);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(420, 50, 510, 640);

        jLabel14.setText("SUPERPODERES");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(420, 20, 110, 16);

        jButton9.setText("(Crear Primero)Agregar poder");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(20, 640, 210, 32);

        jButton10.setText("(Crear Primero)Agregar poder ");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(20, 280, 220, 32);

        jTabbedPane1.addTab("Agregar SuperHeroe", jPanel1);

        poder_descri.setColumns(20);
        poder_descri.setRows(5);
        jScrollPane2.setViewportView(poder_descri);

        buttonGroup2.add(mortal_Si);
        mortal_Si.setSelected(true);
        mortal_Si.setText("Si ");

        buttonGroup2.add(mortal_No);
        mortal_No.setText("No");

        poder_nivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " -------------------------------", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel15.setText("Nivel Poder:");

        jLabel16.setText("Descripcion:");

        jLabel17.setText("Mortal:");

        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setText("CREAR PODER");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(65, 65, 65)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(mortal_Si)
                            .addGap(18, 18, 18)
                            .addComponent(mortal_No, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                        .addComponent(poder_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel18)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poder_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mortal_Si)
                    .addComponent(mortal_No)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar SuperPoder", jPanel3);

        jLabel19.setText("SUPERHEROES");

        jLabel20.setText("SUPERVILLANOS");

        ListaSuperHeroes.setModel(new DefaultListModel());
        ListaSuperHeroes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaSuperHeroesMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(ListaSuperHeroes);

        ListaSuperVillanos.setModel(new DefaultListModel());
        ListaSuperVillanos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaSuperVillanosMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(ListaSuperVillanos);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        Arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(Arbol);

        jButton5.setText("------------------>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("------------------>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6)
                    .addComponent(jScrollPane5)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jButton6)))
                        .addGap(82, 82, 82)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(142, 142, 142))))
                    .addComponent(jScrollPane3))
                .addGap(50, 50, 50))
        );

        jTabbedPane1.addTab("Arbol y Lista", jPanel2);

        tablaSuperheroes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Planeta Origen", "Altura", "Villanos Atrapados", "Poderes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablaSuperheroes);

        TablaSuperVillanos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Planeta Origen", "Altura", "Carcel", "Muertes causadas", "Poderes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(TablaSuperVillanos);

        jLabel21.setText("SUPERHEROES");

        jLabel22.setText("SUPERVILLANOS");

        jButton7.setText("Agregar a equipo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Agregar a equipo");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        superequipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vengadores", "X-men" }));

        villaequipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dark Avengers", " Sinister Six." }));

        jButton11.setText("Eliminar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Eliminar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                    .addComponent(jScrollPane7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(superequipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(villaequipo, 0, 0, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(superequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton11))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(villaequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton12)))
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Agregar a grupo", jPanel4);

        javax.swing.GroupLayout PaginaPrincipalLayout = new javax.swing.GroupLayout(PaginaPrincipal.getContentPane());
        PaginaPrincipal.getContentPane().setLayout(PaginaPrincipalLayout);
        PaginaPrincipalLayout.setHorizontalGroup(
            PaginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaginaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        PaginaPrincipalLayout.setVerticalGroup(
            PaginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaginaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        AgregarHeroe.setText("jMenu2");
        AgregarHeroe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarHeroeMouseClicked(evt);
            }
        });
        AgregarAlArbol.add(AgregarHeroe);

        AgregarVillano.setText("jMenu2");
        AgregarVillano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarVillanoMouseClicked(evt);
            }
        });
        AgregarAlArbolVillano.add(AgregarVillano);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UsuarioT)
                            .addComponent(contrat, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuarioT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(contrat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void llenarTabla() {
        DefaultTableModel po = (DefaultTableModel) tablaSuperpoderes.getModel();
        DefaultTableModel tab = (DefaultTableModel) tablaSuperheroes.getModel();
        DefaultTableModel te = (DefaultTableModel) TablaSuperVillanos.getModel();
        for (int i = te.getRowCount() - 1; i >= 0; i--) {
            te.removeRow(i);
        }
        for (int i = tab.getRowCount() - 1; i >= 0; i--) {
            tab.removeRow(i);
        }
        for (int i = po.getRowCount() - 1; i >= 0; i--) {
            po.removeRow(i);
        }

        for (Poderes i : poderes) {
            Object[] poder = {i.getDescripcion(), i.getMortal(), i.getNivelpoder()};
            po.addRow(poder);
        }
        int y = 0;
        for (Superheroes i : superheroe) {
            String v = convertir(y);
            Object[] poder = {i.getNombre(), i.getEdad(), i.getPlaneta(), i.getAltura(), ((Superheroes) i).getN_villanosAtrapados(), v};
            tab.addRow(poder);
            y++;
        }
        int yy = 0;
        for (Villanos i : villanos) {
            String v = convertir2(yy);
            Object[] poder = {i.getNombre(), i.getEdad(), i.getPlaneta(), i.getAltura(), ((Villanos) i).getCarcel(), ((Villanos) i).getN_muertescausadas(), v};
            te.addRow(poder);
            y++;
        }
        TablaSuperVillanos.setModel(te);
        tablaSuperheroes.setModel(tab);
        tablaSuperpoderes.setModel(po);
    }

    public String convertir2(int i) {
        String u = "";

        for (Poderes j : villanos.get(i).getPoderes()) {
            u += j;
        }

        return u;
    }

    public String convertir(int i) {
        String u = "";

        for (Poderes j : superheroe.get(i).getSuperpoderes()) {
            u += j;
        }

        return u;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
        this.setVisible(false);
         if (UsuarioT.getText().equals("stanlee") && contrat.getText().equals("spiderman99")) {
            PaginaPrincipal.pack();
            PaginaPrincipal.setVisible(true);
            PaginaPrincipal.setLocationRelativeTo(this);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Contraseña o usuario incorrecto");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void super_alturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_super_alturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_super_alturaActionPerformed

    private void villa_alturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_villa_alturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_villa_alturaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Superheroes p = new Superheroes(super_nombre.getText(), super_planeta.getText(), Integer.parseInt(super_edad.getText()), Double.parseDouble(super_altura.getText()));
        superheroe.add(p);
        DefaultListModel modelo = (DefaultListModel) ListaSuperHeroes.getModel();
        modelo.addElement(p);
        llenarTabla();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        boolean u;
        if (mortal_Si.isSelected()) {
            u = true;
        } else {
            u = false;
        }
        String nivele = (String) poder_nivel.getSelectedItem();
        int nivel = Integer.parseInt(nivele);
        Poderes p = new Poderes(nivel, poder_descri.getText(), u);
        poderes.add(p);
        JOptionPane.showMessageDialog(this, "Se agrego exitosamente");
        poder_nivel.setSelectedIndex(0);
        mortal_Si.setSelected(true);
        poder_descri.setText("");
        llenarTabla();
    }//GEN-LAST:event_jButton4ActionPerformed
    public void arbolsuper() {
        if (ListaSuperHeroes.getSelectedIndex() >= 0) {
            DefaultTreeModel modeloARBOL = (DefaultTreeModel) Arbol.getModel();
            DefaultListModel modeloLISTA = (DefaultListModel) ListaSuperHeroes.getModel();
            int posi = ListaSuperHeroes.getSelectedIndex();
            String equipo = superheroe.get(posi).getEquipo();
            System.out.println(" das " + equipo + " dsa");
            if (equipo != null) {
                DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) modeloARBOL.getRoot();
                int centinela = -1, centinela2 = -1;
                for (int i = 0; i < nodo.getChildCount(); i++) {
                    if (nodo.getChildAt(i).toString().equals("Superheroes")) {
                        for (int j = 0; j < nodo.getChildAt(i).getChildCount(); j++) {
                            if (nodo.getChildAt(i).getChildAt(j).toString().equals(superheroe.get(posi).getEquipo())) {
                                ((DefaultMutableTreeNode) nodo.getChildAt(i).getChildAt(j)).add(new DefaultMutableTreeNode(superheroe.get(posi)));
                                modeloARBOL.reload(nodo);
                                centinela2 = 1;
                            }
                        }
                        centinela = 1;
                    }
                }
                System.out.println(centinela + " " + centinela2);
                if (centinela == -1) {
                    DefaultMutableTreeNode n1 = new DefaultMutableTreeNode("Superheroes");
                    modeloARBOL.reload(nodo);
                    nodo.add(n1);
                    if (centinela2 == -1) {
                        DefaultMutableTreeNode n2 = new DefaultMutableTreeNode(superheroe.get(posi).getEquipo());
                        DefaultMutableTreeNode p1 = new DefaultMutableTreeNode(superheroe.get(posi));
                        modeloARBOL.reload(nodo);
                        n1.add(n2);
                        n2.add(p1);
                    }
                }
                if (centinela == 1) {
                    if (centinela2 == -1) {
                        for (int i = 0; i < nodo.getChildCount(); i++) {
                            if (nodo.getChildAt(i).toString().equals("Superheroes")) {
                                for (int j = 0; j < nodo.getChildAt(i).getChildCount(); j++) {
                                    if (nodo.getChildAt(i).getChildAt(j).toString() != (superheroe.get(posi).getEquipo())) {
                                        ((DefaultMutableTreeNode) nodo.getChildAt(i).getChildAt(j)).add(new DefaultMutableTreeNode(superheroe.get(posi)));
                                        modeloARBOL.reload(nodo);

                                    }
                                }
                            }
                        }
                    }
                }
                modeloARBOL.reload();
            } else {
                JOptionPane.showMessageDialog(this, "No tiene equipo");
            }

        } else {
            JOptionPane.showMessageDialog(this,
                    "No hay persona seleccionada");
        }
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        arbolsuper();
    }//GEN-LAST:event_jButton6ActionPerformed

    public void arbolvilla() {
        if (ListaSuperVillanos.getSelectedIndex() >= 0) {
            DefaultTreeModel modeloARBOL = (DefaultTreeModel) Arbol.getModel();
            DefaultListModel modeloLISTA = (DefaultListModel) ListaSuperVillanos.getModel();
            int posi = ListaSuperVillanos.getSelectedIndex();
            String equipo = villanos.get(posi).getEQUIPO();
            System.out.println(" das " + equipo + " dsa");
            if (equipo != null) {
                DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) modeloARBOL.getRoot();
                int centinela = -1, centinela2 = -1;
                for (int i = 0; i < nodo.getChildCount(); i++) {
                    if (nodo.getChildAt(i).toString().equals("Villanos")) {
                        for (int j = 0; j < nodo.getChildAt(i).getChildCount(); j++) {
                            if (nodo.getChildAt(i).getChildAt(j).toString().equals(villanos.get(posi).getEQUIPO())) {
                                ((DefaultMutableTreeNode) nodo.getChildAt(i).getChildAt(j)).add(new DefaultMutableTreeNode(villanos.get(posi)));
                                modeloARBOL.reload(nodo);
                                centinela2 = 1;
                            }
                        }
                        centinela = 1;
                    }
                }
                System.out.println(centinela + " " + centinela2);
                if (centinela == -1) {
                    DefaultMutableTreeNode n1 = new DefaultMutableTreeNode("Villanos");
                    modeloARBOL.reload(nodo);
                    nodo.add(n1);
                    if (centinela2 == -1) {
                        DefaultMutableTreeNode n2 = new DefaultMutableTreeNode(villanos.get(posi).getEQUIPO());
                        DefaultMutableTreeNode p1 = new DefaultMutableTreeNode(villanos.get(posi));
                        modeloARBOL.reload(nodo);
                        n1.add(n2);
                        n2.add(p1);
                    }
                }
                if (centinela == 1) {
                    if (centinela2 == -1) {
                        for (int i = 0; i < nodo.getChildCount(); i++) {
                            if (nodo.getChildAt(i).toString().equals("Villanos")) {
                                for (int j = 0; j < nodo.getChildAt(i).getChildCount(); j++) {
                                    if (nodo.getChildAt(i).getChildAt(j).toString() != (villanos.get(posi).getEQUIPO())) {
                                        ((DefaultMutableTreeNode) nodo.getChildAt(i).getChildAt(j)).add(new DefaultMutableTreeNode(villanos.get(posi)));
                                        modeloARBOL.reload(nodo);

                                    }
                                }
                            }
                        }
                    }
                }
                modeloARBOL.reload();
            } else {
                JOptionPane.showMessageDialog(this, "No tiene equipo");
            }

        } else {
            JOptionPane.showMessageDialog(this,
                    "No hay persona seleccionada");
        }
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        arbolvilla();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Villanos p = new Villanos(villa_nombre.getText(), villa_planeta.getText(), Integer.parseInt(villa_edad.getText()), Double.parseDouble(villa_altura.getText()));
        villanos.add(p);
        DefaultListModel modelo = (DefaultListModel) ListaSuperVillanos.getModel();
        modelo.addElement(p);
        llenarTabla();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int fila = tablaSuperheroes.getSelectedRow();

        if (fila >= 0) {
            if (superheroe.get(fila).getSuperpoderes().size() >= 1) {
                String equipo = (String) superequipo.getSelectedItem();
                System.out.println(equipo);
                superheroe.get(fila).setEquipo(equipo);
            } else {
                JOptionPane.showMessageDialog(this, "No tiene poderes");
            }

        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int fila = TablaSuperVillanos.getSelectedRow();
        if (fila >= 0) {
            if (villanos.get(fila).getPoderes().size() >= 2) {
                String equipo = (String) villaequipo.getSelectedItem();

                villanos.get(fila).setEQUIPO(equipo);
            } else {
                JOptionPane.showMessageDialog(this, "No tiene poderes");
            }

        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        int fila = tablaSuperpoderes.getSelectedRow();
        if (fila >= 0) {

            if (superheroe.get(superheroe.size() - 1).getSuperpoderes().size() <= 3) {
                superheroe.get(superheroe.size() - 1).getSuperpoderes().add(poderes.get(fila));
            }
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int fila = tablaSuperpoderes.getSelectedRow();
        if (fila >= 0) {
            if (superheroe.get(superheroe.size() - 1).getSuperpoderes().size() <= 3) {
                villanos.get(villanos.size() - 1).getPoderes().add(poderes.get(fila));
            }

        }


    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int fila = tablaSuperpoderes.getSelectedRow();
        if (fila >= 0) {
            superheroe.remove(fila);
            llenarTabla();
        }

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        int fila = TablaSuperVillanos.getSelectedRow();
        if (fila >= 0) {
            villanos.remove(fila);
            llenarTabla();
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void ListaSuperHeroesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaSuperHeroesMouseClicked
        if (ListaSuperHeroes.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                AgregarAlArbol.show(evt.getComponent(),
                        evt.getX(), evt.getY());

            }
        }
    }//GEN-LAST:event_ListaSuperHeroesMouseClicked

    private void ListaSuperVillanosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaSuperVillanosMouseClicked
        if (ListaSuperVillanos.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                AgregarAlArbolVillano.show(evt.getComponent(),
                        evt.getX(), evt.getY());

            }
        }
    }//GEN-LAST:event_ListaSuperVillanosMouseClicked

    private void AgregarHeroeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarHeroeMouseClicked
        arbolsuper();
    }//GEN-LAST:event_AgregarHeroeMouseClicked

    private void AgregarVillanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarVillanoMouseClicked
        arbolvilla();
    }//GEN-LAST:event_AgregarVillanoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab5_marcelarivera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab5_marcelarivera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab5_marcelarivera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab5_marcelarivera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab5_marcelarivera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu AgregarAlArbol;
    private javax.swing.JPopupMenu AgregarAlArbolVillano;
    private javax.swing.JMenu AgregarHeroe;
    private javax.swing.JMenu AgregarVillano;
    private javax.swing.JTree Arbol;
    private javax.swing.JList<String> ListaSuperHeroes;
    private javax.swing.JList<String> ListaSuperVillanos;
    private javax.swing.JFrame PaginaPrincipal;
    private javax.swing.JTable TablaSuperVillanos;
    private javax.swing.JTextField UsuarioT;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPasswordField contrat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton mortal_No;
    private javax.swing.JRadioButton mortal_Si;
    private javax.swing.JTextArea poder_descri;
    private javax.swing.JComboBox<String> poder_nivel;
    private javax.swing.JTextField super_altura;
    private javax.swing.JTextField super_edad;
    private javax.swing.JTextField super_nombre;
    private javax.swing.JTextField super_planeta;
    private javax.swing.JComboBox<String> superequipo;
    private javax.swing.JTable tablaSuperheroes;
    private javax.swing.JTable tablaSuperpoderes;
    private javax.swing.JTextField villa_altura;
    private javax.swing.JTextField villa_edad;
    private javax.swing.JTextField villa_nombre;
    private javax.swing.JTextField villa_planeta;
    private javax.swing.JComboBox<String> villaequipo;
    // End of variables declaration//GEN-END:variables
ArrayList<Superheroes> superheroe = new ArrayList();
    ArrayList<Villanos> villanos = new ArrayList();
    ArrayList<Poderes> poderes = new ArrayList();
}
